> ## ****Numpy -> Numerical Python  (2005 - Travis Oliphant)****

In [2]:
import numpy as np


print(np.__version__)
print(np.__doc__)

1.26.4

NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
partic

In [3]:
# Numpy stores data in an array
# An Array is a container used to store the data of same data type
import numpy as np

arr = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
arr.ndim

2

In [4]:
mat = np.matrix([1, 2, 3, 4])   # matrix is a specialized array, and is always 2D (2- dimensional)
type(mat)

numpy.matrix

In [5]:
# ways to convert to an array

np.array(([1, 2, 3], [4, 5, 6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr = [1, 2, 3, 4]
np.asarray(arr)

array([1, 2, 3, 4])

In [7]:
# asanyarray()   -> only converts data that is not a subclass of array, or a type of array, if subclass of array, it will return the same object(pass the operations)


# np.asanyarray(1)
# np.asanyarray(arr)
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [8]:
# shallow copy   -> change in the actual array will also lead to the change in the reference

print(arr)
a = arr
print(a)

# change in the array will also lead to change in a   -> this i because the a is pointing to the reference of the array(arr)

arr[0] = 100
print(arr)
print(a)

[1, 2, 3, 4]
[1, 2, 3, 4]
[100, 2, 3, 4]
[100, 2, 3, 4]


In [9]:
# deep copy   -> change in that array will not lead to change in the copy of the array(a)

print(arr)
print(a)
a = arr.copy()          # it creates a copy of the array and does not points(or have any reference to the array -> it creates a seperate copy)

arr[0] = 1
print(arr)
print(a)

[100, 2, 3, 4]
[100, 2, 3, 4]
[1, 2, 3, 4]
[100, 2, 3, 4]


In [10]:
# more ways to create an array

# from function

arr1 = np.fromfunction(lambda i, j: i == j, (3,3))
print(arr1.ndim)
print(arr1.shape)
arr1

2
(3, 3)


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [11]:
# fromiter -> using iterables
iterable = (i for i in range(5))        # create a new 1-dimensional array from an iterable object
np.fromiter(iterable, int)

array([0, 1, 2, 3, 4])

In [12]:
np.fromstring("1 2 3 4 5", sep=" ")

array([1., 2., 3., 4., 5.])

In [13]:
# generate sequence of numbers
np.arange(1, 10, 0.1)              # returns evenly spaced values, within a given interval

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [14]:
np.linspace(1, 5, 10) # returns(10) evenly spaced numbers over a specified interval

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [15]:
# np.logspace(1, 5, 10)      // defualt base = 10
np.logspace(1, 5, 10, base=2) # returns numbers spaced evenly on a log scale

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [19]:
# zeros

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#ones

np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# n-dimensional array
np.zeros((1, 1, 1, 1, 1, 2, 3))   # this is a (5)n-dimensional array

array([[[[[[[0., 0., 0.],
            [0., 0., 0.]]]]]]])

In [32]:
np.zeros((5, 2, 3))   # this is a (3)n-dimensional array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
np.eye(3)   # Return a 2-D array with ones on the diagonal and zeros everywhere -> Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
# np.empty((1, 2))         # Return a new array of givrn shape and type, without initializing entries
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
# random module

import random
random.choice([1,2,3,4,5,6,7,8,9,10])

6

In [43]:
random.choice('Shivam')

'v'

In [44]:
random.randrange(1, 10)

4

In [45]:
random.random()    # A random number will be generated between (0-1) where 0(included) and 1(excluded)

0.5301833303513543

In [50]:
# random -> shuffle
random.shuffle([1, 2, 3, 4, 5])
list

[4, 5, 1, 3, 2]

In [51]:
# random.uniform
random.uniform(7, 14)

7.340723724577543

In [54]:
np.random.randn(2, 3)

array([[-0.29286963, -1.03392862,  0.94799527],
       [ 1.29200556, -0.16244318, -0.05227035]])

In [86]:
# arr = np.random.randint(1, 5, size=(3, 4))
arr = np.random.randint(1, 5, (3, 4))
arr

array([[4, 4, 3, 4],
       [3, 4, 2, 1],
       [1, 4, 3, 3]])

In [62]:
print(arr.ndim)
print(arr.shape)
print(arr.size)

2
(3, 4)
12


In [65]:
# reshaping the array

arr.reshape(2, 6)   # Remember : always the reshape parameter should be the multiplication of the original array(that is to be reshaped) (here, 2* 6 == 12)
# arr.reshape(2, 5)        # This will not work and will throw an error -> since 2*5 = 10 < 12 (arr.size)

array([[4, 3, 3, 4, 3, 2],
       [4, 4, 2, 3, 1, 4]])

In [66]:
# case when we don't know, what should be the value of the columm (while reshaping -> an array)
arr.reshape(4, -1)            # numpy -> python will auto detect the parameter(argument) suitable for the column

array([[4, 3, 3],
       [4, 3, 2],
       [4, 4, 2],
       [3, 1, 4]])

In [68]:
# case when we don't know, what should be the value of the row (while reshaping -> an array)
arr.reshape(-1, 4)            # numpy -> python will auto detect the parameter(argument) suitable for the row

array([[4, 3, 3, 4],
       [3, 2, 4, 4],
       [2, 3, 1, 4]])

In [79]:
arr.reshape(12,)  # this will reshape the array with 12 -> columns
# arr.reshape(12,1)   # this will reshape the array with 12 rows

array([4, 3, 3, 4, 3, 2, 4, 4, 2, 3, 1, 4])

In [80]:
arr.reshape(2, 6).base             # this will reshape the array to the given dimension but will reflect(show) the original array

array([[4, 3, 3, 4],
       [3, 2, 4, 4],
       [2, 3, 1, 4]])

In [81]:
arr.reshape(2, 2, 3)   # this will reshape the array in 2 dimensions, each containing (2, 3) shape

array([[[4, 3, 3],
        [4, 3, 2]],

       [[4, 4, 2],
        [3, 1, 4]]])

In [87]:
arr.reshape(1, 2, 2, 3)  # this will reshape the array in 2 dimensions, each containing (2, 3) shape, with an outer dimension -> resulting in the creation of 4-dimension array

array([[[[4, 4, 3],
         [4, 3, 4]],

        [[2, 1, 1],
         [4, 3, 3]]]])

In [89]:
arr = np.random.randint(1, 10, (5, 6))
arr

array([[3, 7, 6, 6, 2, 9],
       [2, 9, 7, 1, 7, 2],
       [8, 2, 9, 3, 7, 6],
       [4, 6, 7, 4, 9, 4],
       [4, 9, 8, 3, 1, 4]])

In [93]:
# arr[0:2]   # this will only show the first two rows of the array 
# arr[0:2, [0, 2]]     # this will show only the { 0th & 2nd } column of the array from the starting 2 rows
arr[0:2, 0:3]          # it will show the first three columns of the first two rowds

array([[3, 7, 6],
       [2, 9, 7]])

In [96]:
# performing matrix multiplication on the arrays
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))
print(arr1)
print(arr2)

[[2 1 1]
 [1 2 1]
 [1 2 2]]
[[2 1 1]
 [2 2 1]
 [2 2 1]]


In [98]:
arr1 * arr2    # this is just the index based array multiplication

array([[4, 1, 1],
       [2, 4, 1],
       [2, 4, 2]])

In [99]:
arr1 @ arr2                         # this is the matrix multiplication on the given two arrays

array([[ 8,  6,  4],
       [ 8,  7,  4],
       [10,  9,  5]])

In [101]:
np.dot(arr1, arr2)                    # this is the also another(method) matrix multiplication on the given two arrays

array([[ 8,  6,  4],
       [ 8,  7,  4],
       [10,  9,  5]])

In [103]:
# this is an example of broadcasting(internal broadcasting)
arr1 - 5

# understanding  :
            # internally it will create an array containing (5) only with the same shape(dimension) and the it will add it index wise
            # means -> it will create an array of the same(dimension/ shape) of the { arr1 } containing(5) and then it will add them index wise 

array([[-3, -4, -4],
       [-4, -3, -4],
       [-4, -3, -3]])

In [106]:
arr = np.zeros((3, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [108]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [115]:
new_arr = arr + a           # here the array a of the shape(1, 3) will be broadcasted on every row of the array(arr) of size (3, 3) and will perform index wise addition
new_arr

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [117]:
print(new_arr)
new_arr.T               # this will transpose the given array

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [118]:
print(np.sqrt(new_arr))
print(np.log10(new_arr))
print(np.exp(new_arr))

[[1.         1.41421356 1.73205081]
 [1.         1.41421356 1.73205081]
 [1.         1.41421356 1.73205081]]
[[0.         0.30103    0.47712125]
 [0.         0.30103    0.47712125]
 [0.         0.30103    0.47712125]]
[[ 2.71828183  7.3890561  20.08553692]
 [ 2.71828183  7.3890561  20.08553692]
 [ 2.71828183  7.3890561  20.08553692]]


In [119]:
np.min(new_arr)
np.max(new_arr)

3.0

In [120]:
# flatten()

new_arr.flatten()        # returns the copy of the array reduced to 1-dimension

array([1., 2., 3., 1., 2., 3., 1., 2., 3.])

In [123]:
# expand dimension            -> every time it increases the dimension by 1 at the provided axis(row, col)

# np.expand_dims(new_arr, axis = 0)         # this will increase(expand) the dimensions row wise
np.expand_dims(new_arr, axis = 1)         # this will increase(expand) the dimensions col wise

array([[[1., 2., 3.]],

       [[1., 2., 3.]],

       [[1., 2., 3.]]])

In [131]:
# squeeze()        -> every time it will redice the dimensions by 1 (axis is not necessarily needs to be provided)

np.squeeze(new_arr)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [133]:
np.repeat(new_arr, 4)    # it will repeat every element in the original array by (4) - n times ans will return the array in one-dimension

array([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 1., 1., 1., 1., 2.,
       2., 2., 2., 3., 3., 3., 3., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3.,
       3., 3.])

In [136]:
# np.repeat(new_arr, 4, axis = 1)        # it will repeat the columns by (4) n-times of the original array
np.repeat(new_arr, 4, axis = 0)        # it will repeat the rows by (4) n-times of the original array

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [141]:
# roll -> this is used to roll the array element from the original position to some new position depending upon the (roll -> value (forward, backward))

print(new_arr)
np.roll(new_arr, -1)              # it will shift the element one step backward
# np.roll(new_arr, -2)              # it will shift the element two step backward
# np.roll(new_arr, 1)              # it will shift the element two step forward
# np.roll(new_arr, 2)              # it will shift the element two step forward

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


array([[2., 3., 1.],
       [2., 3., 1.],
       [2., 3., 1.]])

In [144]:
arr = np.array([[1,2], [3, 4], [5, 6], [7, 8]])
print(arr)
np.roll(arr, -1)   # every element in the array will be shifted to one position backward
# np.roll(arr, -2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [148]:
print(arr)

np.roll(arr, 2, axis = 0)         # it will roll up (moves the row forward by 2 steps)  -> similarily we can do this for columns (using -> axis = 1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [149]:
# string array
arr = np.array(["shivam", "kumar"])
arr

array(['shivam', 'kumar'], dtype='<U6')

In [157]:
print(np.char.capitalize(arr))
np.char.upper(arr)

['Shivam' 'Kumar']


array(['SHIVAM', 'KUMAR'], dtype='<U6')

In [164]:
# arr = [[1,2,3], [4,5,6]]
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print("--------------")
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))
print(np.log10(arr))
print(np.exp(arr))
print(np.power(arr, 2))
print(np.mod(arr, arr))       # returns element wise remainder

[[1 2 3]
 [4 5 6]]
--------------
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]


In [169]:
# sorting

arr = np.array([[6, 5, 4], [3, 2, 1]])
print(arr)
np.sort(arr)

[[6 5 4]
 [3 2 1]]


array([[4, 5, 6],
       [1, 2, 3]])

In [179]:
# search sorted     -> finds indixes where elements should be inserted to maintain the order
                    # it will return a particular index for the given array with the provided value to be added, and that given index wil be the place where adding that particular value will not result in making the array unsorted
# this will only work for one-dimensional array( 1D array )
# remember: for geeting the exact index, where addition o the value will not result in making the array unsorted : the given array should be (already) sorted 

arr = np.array([1,2,5,4,7,43,8,7,67,67,486,48,86,357])
arr = np.sort(arr)
np.searchsorted(arr, 3)

2

In [182]:
# count_nonzero    # it will provide the count of the non-zero elements from the given array

arr = np.array([1,2,5,0,7,0,8,0,0,67,0,48,86,0])
np.count_nonzero(arr)

8

In [183]:
arr[arr>0]

array([ 1,  2,  5,  7,  8, 67, 48, 86])

In [184]:
np.where(arr>0)         # it will return the indexes

(array([ 0,  1,  2,  4,  6,  9, 11, 12], dtype=int64),)

In [187]:
np.extract(arr>0, arr)        # it will return the exact values

array([ 1,  2,  5,  7,  8, 67, 48, 86])

In [189]:
# byte representation
arr.byteswap()         # it will return the bytes representation of the element of the array

array([  16777216,   33554432,   83886080,          0,  117440512,
                0,  134217728,          0,          0, 1124073472,
                0,  805306368, 1442840576,          0])

In [192]:
# matrix -> 2D Array

import numpy.matlib as nm
print(nm.zeros(5))                # it will create a matrix only, while operating

print(np.zeros(5))
nm.ones(5)

[[0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]


matrix([[1., 1., 1., 1., 1.]])

In [199]:
arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randint(1, 10, (3, 3))
print(arr1)
print(arr2)

[[9 7 9]
 [4 6 7]
 [2 9 4]]
[[4 5 1]
 [3 9 6]
 [5 8 8]]


In [200]:
# numpy linear algebra

# Determinant       -> determinant of a matrix
np.linalg.det(arr1)

-149.0

In [202]:
# inverse    -> inverse of a matrix
np.linalg.inv(arr1)

array([[ 0.26174497, -0.3557047 ,  0.03355705],
       [ 0.01342282, -0.12080537,  0.18120805],
       [-0.16107383,  0.44966443, -0.17449664]])

In [203]:
# Liear Algebra -> solving equations

a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])        # these are the values of the coefficients
b = np.array([16, 8, 0])               # these will be the values of the RHS of the equations
print(a)
print(b)

[[ 7.   5.3 -3. ]
 [ 3.  -5.   2. ]
 [ 5.   3.  -7. ]]
[16  8  0]


In [204]:
np.linalg.solve(a, b)          # this will return the values of {x, y, z}  -> this is after solving the equations

array([2.59630607, 0.84432718, 2.21635884])